language: php

php:
    - 5.4
    - 5.5
    - 5.6

install:
    - composer install --dev --no-interaction --prefer-source

before_script:
    - mkdir -p build/logs
    - mysql -uroot -e 'SET @@global.sql_mode = TRADITIONAL; CREATE DATABASE runalyze_unittest;';
    - mysql runalyze_unittest < inc/install/structure.sql

script:
    - phpunit --colors -c tests/config.xml --coverage-clover build/logs/clover.xml

after_script:
    - wget https://scrutinizer-ci.com/ocular.phar && php ocular.phar code-coverage:upload --format=php-clover build/logs/clover.xml
