language: php
sudo: required

php:
    - 5.6
    - 7.0

install:
    - composer install --prefer-dist --no-interaction

before_script:
    - cp app/config/default_config.yml data/config.yml
    - mkdir -p build/logs
    - mysql -uroot -e 'SET @@global.sql_mode = TRADITIONAL; CREATE DATABASE runalyze_unittest; CREATE DATABASE runalyze_test;';
    - php bin/console --env=test doctrine:schema:update --force --complete
    - mysql runalyze_unittest < inc/install/structure.sql

    - mysql -e "SHOW VARIABLES LIKE 'max_allowed_packet';"
    - echo "[server]\nmax_allowed_packet=64M" | sudo tee -a /etc/mysql/my.cnf
    - sudo service mysql restart
    - mysql -e "SET GLOBAL wait_timeout=300;"
    - mysql -e "SHOW VARIABLES LIKE 'max_allowed_packet';"

script:
    - vendor/bin/phpunit --colors -c tests/config.xml --coverage-clover build/logs/clover.xml

after_script:
    - wget https://scrutinizer-ci.com/ocular.phar && php ocular.phar code-coverage:upload --format=php-clover build/logs/clover.xml

matrix:
  include:
    - php: 5.6
      env: DB=mariadb
      addons:
        mariadb: 5.5
    - php: 7.0
      env: DB=mariadb
      addons:
        mariadb: 5.5

    - php: 5.6
      env: DB=mariadb
      addons:
        mariadb: 10.0
    - php: 7.0
      env: DB=mariadb
      addons:
        mariadb: 10.0
