parameters:
  locale: en
  database_host: 127.0.0.1
  database_prefix: runalyze_
  database_port: 3306
  database_name: runalyze
  database_user: root
  database_password:
  secret: please_change_this_secret
  update_disabled: no
  user_can_register: true
  user_disable_account_activation: false
  maintenance: false
  garmin_api_key:
  openweathermap_api_key:
  darksky_api_key:
  nokia_here_appid:
  nokia_here_token:
  thunderforest_api_key:
  mapbox_api_key:
  geonames_username:
  perl_path: /usr/bin/perl
  python3_path: /usr/bin/python3
  rsvg_path: /usr/bin/rsvg-convert
  inkscape_path: /usr/bin/inkscape
  ttbin_path: ../call/perl/ttbincnv
  sqlite_mod_spatialite: libspatialite.so.5
  mail_sender:
  mail_name:
  smtp_host: localhost
  smtp_port: 25
  smtp_security:
  smtp_username:
  smtp_password:
  backup_storage_period: 5
  poster_storage_period: 5
  router.request_context.host: localhost
  router.request_context.scheme: http
  router.request_context.base_url:
