security:
    encoders:
        Runalyze\Bundle\CoreBundle\Entity\Account:
            id: app.sha256salted_encoder

    providers:
        runalyzeuser:
            entity:
                class: CoreBundle:Account

    firewalls:
        default:
            anonymous: ~
            http_basic: ~
            provider:  runalyzeuser
            switch_user: { role: ROLE_ADMIN, parameter: _switch_user }
            logout:
                path:   /logout
                target: /
            form_login:
                login_path: login
                check_path: login_check
                csrf_token_generator: security.csrf.token_manager
                use_referer: true
            remember_me:
                secret:   '%secret%'
                lifetime: 604800 # 1 week in seconds
                path:     /

        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false

        setup:
            pattern:  ^/(update|install)
            security: false
    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
